name: tests

on:
  push:
    branches:
      - main
  pull_request: null

jobs:
  tests:
    name: tests
    runs-on: "ubuntu-latest"
    steps:
      - name: generate token
        id: generate_token
        uses: conda-forge/github-app-token@e3ab451d57e120b956292a1fa1d21fe4ba171c36 # pin@e3ab451d57e120b956292a1fa1d21fe4ba171c36
        with:
          app_id: ${{ secrets.CF_CURATOR_APP_ID }}
          private_key: ${{ secrets.CF_CURATOR_PRIVATE_KEY }}

      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@ce177499ccf9fd2aded3b0426c97e5434c2e8a73 # pin@0.6.0
        with:
          access_token: ${{ steps.generate_token.outputs.token }}

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          fetch-depth: 100

      - name: install micromamba
        uses: mamba-org/provision-with-micromamba@3c96c0c27676490c63c18bc81f5c51895ac3e0e6 # pin@main

      - name: install code
        shell: bash -l {0}
        run: |
          python -m pip install -e .

      - name: lint
        shell: bash -l {0}
        run: |
          flake8 conda_forge_artifact_validation
          flake8 bin/*

      - name: test
        shell: bash -l {0}
        run: |
          pytest -vvs conda_forge_artifact_validation

      - name: run cli help commands
        shell: bash -l {0}
        run: |
          conda-forge-validate-artifact --help
          conda-forge-generate-validate-yamls --help

      - name: run generate smoke test
        shell: bash -l {0}
        run: |
          conda-forge-generate-validate-yamls --test
          git diff

      - name: run cli utils tests
        shell: bash -l {0}
        run: |
          wget -q https://conda.anaconda.org/conda-forge/osx-64/numpy-1.19.4-py36hcf5569d_1.tar.bz2
          wget -q https://conda.anaconda.org/conda-forge/linux-64/cf-autotick-bot-test-package-0.10-py36h9f0ad1d_2.tar.bz2
          wget -q https://conda.anaconda.org/conda-forge/linux-64/freud-0.11.0-py27h3e44d54_0.tar.bz2
          pytest -vvs scripts/test_cli_utils.py
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
